---
version: '3.9'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptimekuma
    volumes:
      - ${UK_PATH}:/app/data
      - /var/run/docker.sock:/var/run/docker.sock      
    ports:
      - 3001:3001
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"    

networks:
  default:
    name: ${NETWORK}
    external: true