---
version: '3.9'

services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${LOCALTIME_PATH}:/etc/localtime:ro
      - ${DOCKER_SOCK_PATH}:/var/run/docker.sock:ro
      - ${PORTAINER_DATA_PATH}:/data
    ports:
      - 9000:9000
    restart: unless-stopped

networks:
  default:
    name: ${NETWORK}
    external: true